## numbers

### `fromBinary(number value)`
Converts `value` from binary to decimal.

*Example*

.DataSonnet map:
------------------------
ds.numbers.fromBinary(1100100)
------------------------
.Result
------------------------
100
------------------------

*Version*:

Created: 1.0.0

### `fromHex(number value)`
Converts `value` from hex to decimal.

*Example*

.DataSonnet map:
------------------------
ds.numbers.fromHex(64)
------------------------
.Result
------------------------
100
------------------------

*Version*:

Created: 1.0.0

### `fromRadixNumber(number value, number baseAsBinary)`
Converts `value` to a decimal with the base `baseAsBinary`.

*Example*

.DataSonnet map:
------------------------
ds.numbers.fromRadixNumber(1101000, 2)
------------------------
.Result
------------------------
104
------------------------

*Version*:

Created: 1.0.0

### `toBinary(number value)`
Converts `value` from decimal to binary.

*Example*

.DataSonnet map:
------------------------
ds.numbers.toBinary(100)
------------------------
.Result
------------------------
"1100100"
------------------------

*Version*:

Created: 1.0.0

### `toHex(number value)`
Converts `value` from decimal to hex.

*Example*

.DataSonnet map:
------------------------
ds.numbers.toHex(100)
------------------------
.Result
------------------------
"64"
------------------------

*Version*:

Created: 1.0.0

### `toRadixNumber(number value, number baseAsDecimal)`
Converts `value` to a number with the base `baseAsDecimal`.

*Example*

.DataSonnet map:
------------------------
ds.numbers.toRadixNumber(104, 2)
------------------------
.Result
------------------------
"1101000"
------------------------

*Version*:

Created: 1.0.0

